[package]
name = "lo-shu"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
lazy_static = "1.4.0"
rayon = "1.6.1"

[dev-dependencies]
criterion = "0.4.0"
iai = "0.1.1"

[[bench]]
name = "lib_bench"
harness = false

[[bench]]
name = "mpsc_bench"
harness = false

[[bench]]
name = "test_order_three"
harness = false

[[bench]]
name = "test_order_three_mpsc"
harness = false

[[bench]]
name = "core_compress"
harness = false

[[bench]]
name = "core_check_compressed"
harness = false

[[bench]]
name = "core_check"
harness = false
