[package]
name = "lo-shu"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
rayon = "1.6.1"

[dev-dependencies]
criterion = "0.4.0"
iai = "0.1.1"

[[bench]]
name = "lib_bench"
harness = false

[[bench]]
name = "perf_function"
harness = false
